.MODEL SMALL
.DATA
.CODE

NUM DW 8
RESULT DW (?) ; INITIALIZE MEMORY FOR THE RESULT
MAIN PROC
MOV AX, @DATA ; INITIALIZE DATA SEGMENT
MOV DS, AX
MOV AX, 01 ; INITIALIZE RESULT AS 01 IF THE NUMBER IS 0
MOV CX, NUM ; INITIALIZE NUMBER
CMP CX, 00 ; CHECK WHETHER NUMBER IS 0
JE LOOP1 ; YES, TERMINATE PROGRAM
MOV BX, CX ; SAVE THE NUMBER IN BX
CALL FACT ; CALL FACTORIAL PROCEDURE
LOOP1:
MOV RESULT, AX ; SAVE FACTORIAL RESULT
MOV AH, 4CH
INT 21H
MAIN ENDP ; END MAIN PROCEDURE
FACT PROC
CMP BX, 01
JZ LOOP2
PUSH BX
DEC BX
CALL FACT ; CALL FACTORIAL

PROCEDURE POP BX
MUL BX
RET ; RETURN CALLED PROGRAM

LOOP2:
MOV AX, 01 ; INITIALIZE AX REGISTER TO 01
RET ; RETURN CALLED PROGRAM
FACT ENDP ; END FACTORIAL PROCEDURE
END